### ISSUE TITLE
Hostname isn't always the same as InetAddress.getLocalHost().getCanonicalHostName()

### ISSUE THREAD

**Issue by buckett** [getsentry/raven-java#138] opened 2015-05-18 13:24 UTC
`InetAddress.getLocalHost().getCanonicalHostName()` will return the name for the default interface interface under linux. This isn't always the same as the hostname that a machine has.

Locally we are using docker to deploy multiple JVMs that use the same IP address as their default route, this results in them all thinking they are the same host, even though they have different hostnames.

**Comment by buckett** [comment] 2015-05-18 13:25
Is it possible to have the hostname pulled from environmental variable `HOSTNAME`?

**Comment by anujku** [comment] 2015-05-18 17:28
I think you are looking for this - https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/event/EventBuilder.java#L216

**Comment by buckett** [comment] 2015-05-18 19:39
@anujku Thanks, but I was hoping that raven-java might consider supporting it itself.

**Comment by ColinHebert** [comment] 2015-05-18 22:22
It is indeed a problem. Google App Engine had the same kind of issue.

The way to get around this is to use a custom `EvenBuilderHelper` that will override the hostname with the value you prefer. (see https://github.com/getsentry/raven-java/blob/master/raven-appengine/src/main/java/net/kencochrane/raven/appengine/event/helper/AppEngineEventBuilderHelper.java).

You then need to extend `DefaultRavenFactory` to add something like this:

```
    @Override
    public Raven createRavenInstance(Dsn dsn) {
        Raven ravenInstance = super.createRavenInstance(dsn);
        ravenInstance.addBuilderHelper(new MyCustomEventBuilderHelper());
        return ravenInstance;
    }
```


This way you can intercept events as they're being built and inject the value you want.

**Comment by tkaemming** [comment] 2016-03-07 23:12
I am going to close this as it's essentially a duplicate of GH-175 which will provide a more direct method of overriding the hostname retrieval method.

**Closed by tkaemming** 2016-03-07 23:12 UTC
